// Word data files (words_pt.json, words_es.json, words_fr.json, words_it.json)
// are generated by the data extraction script in Phase 1.
// This file is a placeholder — delete once data files are in place.
export {}
